/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/entities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_entities"];
    put?: never;
    post: operations["create_entity"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/entities/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_entity"];
    put: operations["update_entity"];
    post?: never;
    delete: operations["delete_entity"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/entities/{id}/context": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_entity_context"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/entities/{id}/drift": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_entity_drift"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/export.jsonl": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Line-delimited JSON export of every schema, entity, and relation belonging to the tenant, one `{"kind":"schema"|"entity"|"relation","record":{...}}` object per line. */
    get: operations["export_jsonl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/import.jsonl": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Line-delimited JSON import in the same format `GET /api/export.jsonl` produces: one `{"kind":"schema"|"entity"|"relation","record":{...}}` object per line.
     *     Requires `SchemaScope` (rather than `WriteScope`) since an import can create schemas, which is itself a schema-scope-only operation elsewhere in the API.
     * @description Runs as a single transaction: either every record in the body is applied, or (on the first error) none of it is and the request fails with that error.
     */
    post: operations["import_jsonl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_members"];
    put?: never;
    post: operations["add_member"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/migration-jobs/{job_id}/undo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["undo_migration_job"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_relations"];
    put?: never;
    post: operations["create_relation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_relation"];
    put?: never;
    post?: never;
    delete: operations["delete_relation"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/relations/{id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["set_relation_status"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schemas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_schemas"];
    put?: never;
    post: operations["create_schema"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schemas/active/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_active_schema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schemas/active/{name}/entity-types/{entity_type}/json-schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_entity_type_json_schema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schemas/active/{name}/fill-defaults": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["fill_defaults"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schemas/active/{name}/migration-dry-run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["migration_dry_run"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schemas/{schema_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_schema_by_id"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["search_entities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/system/maintenance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_maintenance"];
    put: operations["set_maintenance"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/template-library": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_template_library"];
    put?: never;
    post: operations["create_template"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/template-library/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_template_library_item"];
    put: operations["update_template"];
    post?: never;
    delete: operations["delete_template"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/template-library/{id}/fork": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["fork_template_library_item"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_templates"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_template"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_workspaces"];
    put?: never;
    post: operations["create_workspace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_workspace"];
    put?: never;
    post?: never;
    delete: operations["delete_workspace"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/setup/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["setup_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddMemberRequest: {
      /**
       * @description Must already have an account (created via `/auth/signup`): this endpoint attaches an *existing* user to the caller's tenant, it never creates one.
       *     To bring in someone with no account yet, issue them an invite instead.
       */
      email: string;
      role: components["schemas"]["MembershipRole"];
    };
    /**
     * @description A DTO that exists only to describe the error response shape in the OpenAPI document.
     *     Actual response bodies are built individually by `ApiError::into_response`, so this type's values are never used: it exists purely for schema generation.
     */
    ApiErrorBody: {
      error: components["schemas"]["ApiErrorDetail"];
    };
    ApiErrorDetail: {
      details?: components["schemas"]["ValidationDetail"][] | null;
      hint?: string | null;
      message: string;
    };
    /**
     * @description Permission level held by an API key.
     *     Declaration order feeds the derived `Ord`, so any code relying on the `Read < Write < Schema` hierarchy (a higher scope subsumes lower ones) depends on this exact ordering.
     *     The `serde` representation matches the DB `scope` column ('read'/'write'/'schema'), so REST/MCP adapters don't need a separate mapping.
     * @enum {string}
     */
    ApiKeyScope: "read" | "write" | "schema" | "migration";
    ArrayItems: {
      properties?: Record<string, never> | null;
      type: string;
    };
    CreateEntityRequest: {
      data: Record<string, never>;
      entity_type: string;
      schema_name: string;
    };
    CreateRelationRequest: {
      properties?: Record<string, never> | null;
      relation_type: string;
      /** Format: uuid */
      source_id: string;
      /** Format: uuid */
      target_id: string;
    };
    /**
     * @description Either an inline schema definition, or a reference to a template.
     *
     *     `template_id` accepts both kinds of template, because a caller holding an id should not have to know which kind it is:
     *       * a built-in id (`"task-management"`, see `GET /api/templates`), served from the binary
     *       * a UUID from the tenant's template library (`GET /api/template-library`), which is where
     *         a template copied from another tenant lands
     *
     *     Untagged so existing clients posting a flat `MetaSchemaDefinition` body keep working unchanged.
     */
    CreateSchemaRequest:
      | components["schemas"]["MetaSchemaDefinition"]
      | {
          template_id: string;
        };
    CreateSchemaResponse: {
      diff: components["schemas"]["VersioningDiff"];
      schema: components["schemas"]["SchemaRecord"];
    };
    CreateTemplateRequest: {
      author?: string | null;
      definition: components["schemas"]["MetaSchemaDefinition"];
      description?: string | null;
      locale?: string | null;
      name: string;
      tags?: string[];
    };
    CreateWorkspaceRequest: {
      /**
       * Format: int32
       * @description Cap on the number of entities this workspace may hold.
       *     Omit for unlimited.
       */
      max_entities?: number | null;
      name: string;
      /**
       * Format: uuid
       * @description Schema to associate with this workspace.
       *     Omit to leave it unset.
       */
      schema_id?: string | null;
    };
    /** @description A field an entity predates. */
    DriftField: {
      name: string;
      /**
       * @description Whether the active version marks it required.
       *     A required field an old entity lacks is the case worth surfacing: the entity is valid under its own version and would not be under the current one.
       */
      required: boolean;
      /**
       * @description The field's type in the active version, so a caller can tell what would go there.
       *     Serializes to the same spelling the schema uses.
       */
      type: components["schemas"]["FieldTypeName"];
    };
    DryRunByType: {
      /** Format: int64 */
      behind: number;
      entity_type: string;
      /** @description The required fields those entities lack, so the report names the work rather than only counting it. */
      missing_required: string[];
      /** Format: int64 */
      needs_values: number;
    };
    /**
     * @description How one entity stands relative to the active version of its schema.
     *
     *     Entities are migrated lazily: a schema gaining a version does not rewrite the rows written against earlier ones, and an update validates against the version the entity was created with.
     *     That is deliberate: it is what stops a schema change from invalidating stored data.
     *     But it leaves a reader unable to tell whether a field is absent because nobody filled it in or because it did not exist when the entity was written.
     */
    EntityDrift: {
      /**
       * Format: int32
       * @description The newest active version of the same schema.
       */
      active_schema_version: number;
      /** Format: uuid */
      entity_id: string;
      entity_type: string;
      /**
       * @description Fields the active version defines that this entity's version did not.
       *     Empty when the entity is current, and empty as well when the newer version only changed fields the entity already carries.
       */
      missing_fields: components["schemas"]["DriftField"][];
      /**
       * Format: int32
       * @description The version this entity was written against.
       */
      schema_version: number;
    };
    /**
     * @description A row in the `entities` table.
     *     `embedding` is managed separately by the search/embedding pipeline, so this module's CRUD doesn't touch it.
     *     `created_by`/ `updated_by` are `None` for entities touched by an unattributed (service/automation) API key, since there's no user to record.
     *     `Deserialize` is derived so this can be read back from a JSONL export (see `models::import`); import treats `id`, `schema_version`, `created_at`/`updated_at` as informational only (a fresh row is always inserted).
     */
    EntityRecord: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      created_by?: string | null;
      data: Record<string, never>;
      entity_type: string;
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      schema_id: string;
      /** Format: int32 */
      schema_version: number;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      updated_by?: string | null;
      /** Format: uuid */
      workspace_id: string;
    };
    EntityTypeDef: {
      description?: string | null;
      fields: {
        [key: string]: components["schemas"]["FieldDef"];
      };
    };
    /**
     * @description Field definition using standard JSON Schema keywords.
     *     Unknown `x-` attributes are preserved via `extra` (flattened) so that older clients don't drop fields they don't recognize yet.
     */
    FieldDef: Record<string, never> & {
      default?: Record<string, never> | null;
      description?: string | null;
      enum?: string[] | null;
      format?: string | null;
      items?: null | components["schemas"]["ArrayItems"];
      /** Format: int64 */
      maxItems?: number | null;
      /** Format: int64 */
      maxLength?: number | null;
      /** Format: double */
      maximum?: number | null;
      /** Format: int64 */
      minItems?: number | null;
      /** Format: int64 */
      minLength?: number | null;
      /** Format: double */
      minimum?: number | null;
      pattern?: string | null;
      properties?: Record<string, never> | null;
      required?: boolean;
      type: components["schemas"]["FieldTypeName"];
      uniqueItems?: boolean;
      "x-embed"?: boolean;
      "x-ui"?: Record<string, never> | null;
    };
    /** @enum {string} */
    FieldTypeName: "string" | "number" | "integer" | "boolean" | "array" | "object";
    /** @description What filling defaults did. */
    FillDefaultsReport: {
      /**
       * Format: int64
       * @description Entities that gained at least one value.
       */
      filled: number;
      /**
       * Format: uuid
       * @description Groups the snapshots taken, so this run can be undone as one.
       */
      job_id: string;
      schema_name: string;
      /**
       * Format: int64
       * @description Entities that needed a value the active version defines no default for.
       *     Left untouched and counted, because inventing one would be worse than leaving the field absent: a value nobody chose is indistinguishable from one someone did.
       */
      skipped_no_default: number;
      /** @description The fields those entities still lack. */
      still_missing: string[];
    };
    ForkTemplateRequest: {
      name: string;
    };
    /**
     * @description Outcome of a successful `import_jsonl` call: how many records of each kind were inserted.
     *     Since the whole import runs in one transaction (see `import_jsonl`), a non-empty `errors` here never coexists with partially-applied data: either every record listed by `errors` (and everything after it) was rolled back along with it, or `errors` is empty and every counted record is committed.
     */
    ImportResult: {
      /** Format: int64 */
      entities: number;
      errors: string[];
      /** Format: int64 */
      relations: number;
      /** Format: int64 */
      schemas: number;
    };
    LoginRequest: {
      email: string;
      password: string;
      /**
       * Format: uuid
       * @description Which of the account's workspaces to issue an API key for: a key is always scoped to exactly one workspace, same as one created through `admin create-api-key`.
       *     Omit this when the account can only ever log into one workspace (true by default, since `YORISHIRO_MAX_TENANTS` defaults to a single tenant with one workspace); it resolves automatically.
       *     An account with access to more than one workspace must specify which one explicitly (422 otherwise), and that refusal lists the candidates so the caller does not have to look an id up elsewhere.
       */
      workspace_id?: string | null;
    };
    LoginResponse: {
      /**
       * @description The freshly issued API key's plaintext.
       *     Shown only in this response: only its hash is ever persisted, so it cannot be recovered afterward.
       */
      api_key: string;
      /** Format: uuid */
      api_key_id: string;
      scope: components["schemas"]["ApiKeyScope"];
      /** Format: uuid */
      user_id: string;
      /** Format: uuid */
      workspace_id: string;
    };
    /**
     * @description The state as the API reports it.
     *     `MaintenanceState` is the repository's own type and is not serialisable, so the wire shape is declared here rather than deriving onto core's model: the two are free to differ, and this one is a published contract.
     */
    MaintenanceResponse: {
      /** @description `off`, `read-only` or `full-lock`. */
      mode: string;
      /**
       * @description Why, when whoever set it said.
       *     Absent when nothing was given.
       */
      reason?: string | null;
      /**
       * Format: int32
       * @description Seconds a refused caller is told to wait, sent as `Retry-After` on the refusal itself.
       */
      retry_after: number;
    };
    MembershipRecord: {
      display_name?: string | null;
      email: string;
      role: components["schemas"]["MembershipRole"];
      /** Format: uuid */
      user_id: string;
    };
    /**
     * @description Mirrors the `identity.tenant_memberships.role` check constraint (`owner`/`admin`/`member`/`viewer`).
     * @enum {string}
     */
    MembershipRole: "owner" | "admin" | "member" | "viewer";
    MetaSchemaDefinition: {
      description?: string | null;
      entity_types: {
        [key: string]: components["schemas"]["EntityTypeDef"];
      };
      name: string;
      relation_types?: {
        [key: string]: components["schemas"]["RelationTypeDef"];
      };
    };
    /**
     * @description What a batch migration would find, without doing it.
     *
     *     Migration is lazy: an entity keeps validating against the version it was written with, so a workspace accumulates entities spread across versions.
     *     This counts them before anything is touched, because the useful question before a migration is how much of the corpus it would have to fill in: a number that decides whether defaults suffice or whether the work needs a person.
     */
    MigrationDryRun: {
      /**
       * Format: int32
       * @description The version everything would be brought to.
       */
      active_version: number;
      /**
       * Format: int64
       * @description On an older version, but missing no field the active version requires: they validate as they stand and only their version marker is behind.
       */
      behind_but_valid: number;
      /** @description Per entity type, so an operator can see whether the work is spread or concentrated. */
      by_entity_type: components["schemas"]["DryRunByType"][];
      /**
       * Format: int64
       * @description Already on the active version.
       *     Nothing to do for these.
       */
      current: number;
      /**
       * Format: int64
       * @description On an older version and missing at least one field the active version requires.
       *     These are what a migration has to fill in, and what mode A's defaults or mode B's inference would be for.
       */
      needs_values: number;
      schema_name: string;
      /** Format: int64 */
      total_entities: number;
    };
    RecallContext: {
      /** @description The requested entity, always with its full `data`. */
      entity: components["schemas"]["EntityRecord"];
      /**
       * @description Flat list of every neighbor found within `depth` hops, each tagged with its `hop_distance`.
       *     A neighbor reachable via more than one path is only reported once, at the shortest hop_distance it was found at.
       */
      relations: components["schemas"]["RecallRelation"][];
      /** @description `true` when more neighbors exist at some hop than `limit` allowed to be included there. */
      truncated: boolean;
    };
    RecallRelation: {
      direction: string;
      /**
       * Format: int32
       * @description How many hops away from the requested entity this neighbor is (1 = direct neighbor, 2 = neighbor-of-neighbor, etc).
       */
      hop_distance: number;
      /**
       * @description The connected entity.
       *     Shallow (only `x-embed` fields in `data`) by default; pass `full: true` to `recall_context` to get every field instead.
       */
      neighbor: components["schemas"]["EntityRecord"];
      relation_type: string;
    };
    RelationRecord: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      properties: Record<string, never>;
      relation_type: string;
      /** Format: uuid */
      source_id: string;
      /**
       * @description `active`, `deprecated` or `archived`.
       *     Traversal follows `active` relations only.
       */
      status: string;
      /** Format: uuid */
      target_id: string;
      /** Format: uuid */
      workspace_id: string;
    };
    RelationTypeDef: {
      description?: string | null;
      source: string;
      target: string;
    };
    /**
     * @description Represents a row in the `schemas` table.
     *     `definition` is JSONB in the DB, but the application layer always treats it as a parsed `MetaSchemaDefinition`.
     */
    SchemaRecord: {
      /** Format: date-time */
      created_at: string;
      definition: components["schemas"]["MetaSchemaDefinition"];
      /** Format: uuid */
      id: string;
      name: string;
      origin_snapshot?: null | components["schemas"]["MetaSchemaDefinition"];
      /** @description `linked` while the origin is still there to follow, `detached` otherwise, including for every schema that never had one. */
      origin_status?: string;
      /**
       * Format: uuid
       * @description The template this schema was created from, when it was created from one.
       *     `None` for a schema written by hand, and `None` again once that template is deleted.
       *
       *     `default` on deserialize for the same reason as `workspace_id`: this type doubles as the JSONL export record, and an export taken before the column existed carries no such field.
       */
      origin_template_id?: string | null;
      status: string;
      /** Format: uuid */
      tenant_id: string;
      /** Format: int32 */
      version: number;
      /**
       * Format: uuid
       * @description The workspace that owns this schema.
       *     Schemas are per workspace: applying a template gives a workspace its own copy, so a sibling workspace's edits do not reach it.
       *
       *     `default` on deserialize because this type is also the JSONL export record, and an export taken before schemas became workspace-scoped carries no such field.
       *     Import assigns the destination workspace regardless (it remaps every id it reads), so the value in the file is never the one that lands.
       */
      workspace_id?: string;
    };
    /**
     * @description A row in a schema listing.
     *     A lightweight summary that omits the `definition` body, used as the entry point for MCP clients (LLMs) to discover what schemas exist for a tenant.
     */
    SchemaSummary: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      name: string;
      status: string;
      /** Format: int32 */
      version: number;
    };
    SearchHit: {
      /**
       * Format: double
       * @description pgvector cosine distance (the `<=>` operator).
       *     Closer to 0 means more similar.
       *     `None` when the entity has no embedding and was only surfaced through the pg_trgm fuzzy text match on `query_text`.
       */
      distance?: number | null;
      entity: components["schemas"]["EntityRecord"];
    };
    SetMaintenanceRequest: {
      /** @description `off`, `read-only` or `full-lock`, spelled as the CLI spells them. */
      mode: string;
      /** @description Shown to refused callers instead of the generic message. */
      reason?: string | null;
      /**
       * Format: int32
       * @description Defaults to the same 300 seconds `admin maintenance` uses.
       */
      retry_after?: number | null;
    };
    SetRelationStatusRequest: {
      /** @description `active`, `deprecated` or `archived`. */
      status: string;
    };
    /**
     * @description Unlike `/auth/signup`, which redeems an invite into an *existing* tenant, this creates the deployment's first tenant/workspace from scratch: there is no one to invite from yet.
     *     Only email/password are asked for (see `web/`'s setup screen); the tenant and workspace get fixed default names, matching a self-hosted deployment's "one operator, one tenant" reality.
     */
    SetupRequest: {
      display_name?: string | null;
      email: string;
      password: string;
    };
    SetupResponse: {
      /** @description A freshly issued API key, scoped to the new owner account: shown only here, same as `/auth/login`'s, so the setup screen can log straight into the dashboard afterward. */
      api_key: string;
      email: string;
      /** Format: uuid */
      tenant_id: string;
      /** Format: uuid */
      user_id: string;
      /** Format: uuid */
      workspace_id: string;
    };
    SetupStatusResponse: {
      /** @description True when the wizard is enabled and no tenant exists yet: the client should show the setup form instead of the login form. */
      setup_required: boolean;
    };
    /**
     * @description These two endpoints are the only ones in the whole API reachable without a bearer token, by design, since their entire purpose is to hand one out.
     *     They read/write `identity.users`/`identity.tenant_memberships`/`identity.invites` through `state.identity_pool` (the admin/migration-role pool) rather than `state.tenant_db`, exactly like the admin CLI, since no tenant/workspace context exists yet for RLS to scope by.
     */
    SignupRequest: {
      display_name?: string | null;
      /** @description The plaintext token from an `admin create-invite` invitation. */
      invite_token: string;
      password: string;
    };
    SignupResponse: {
      email: string;
      role: components["schemas"]["MembershipRole"];
      /** Format: uuid */
      tenant_id: string;
      /** Format: uuid */
      user_id: string;
      /**
       * @description The workspaces the new member can now log into.
       *     The client picks one and passes its id to `/auth/login`.
       */
      workspaces: components["schemas"]["WorkspaceSummary"][];
    };
    /**
     * @description A user-contributed schema template stored in `identity.templates`.
     *     Distinct from the built-in templates in `crate::templates` (shipped with the binary, served from memory):
     *     this is the tenant-scoped, DB-backed template library.
     */
    TemplateRecord: {
      author?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      created_by?: string | null;
      definition: components["schemas"]["MetaSchemaDefinition"];
      description?: string | null;
      /** Format: uuid */
      fork_of?: string | null;
      /** Format: uuid */
      id: string;
      locale?: string | null;
      name: string;
      tags: string[];
      /** Format: uuid */
      tenant_id: string;
      /** Format: date-time */
      updated_at: string;
      visibility: string;
    };
    /** @description Summary of a built-in schema template, returned by `list_templates` so a caller can pick a `template_id` without first fetching every template's full definition. */
    TemplateSummary: {
      description?: string | null;
      id: string;
      name: string;
    };
    /** @description What undoing a job put back. */
    UndoReport: {
      /** Format: uuid */
      job_id: string;
      /**
       * Format: int64
       * @description Snapshots whose entity no longer exists.
       *     Counted rather than treated as an error: a batch partially undone leaves a workspace in a state nobody chose, and an entity deleted since is not a reason to refuse the rest.
       */
      missing: number;
      /**
       * Format: int64
       * @description Entities restored to the data they held before.
       */
      restored: number;
    };
    UpdateEntityRequest: {
      data: Record<string, never>;
    };
    UpdateTemplateRequest: {
      definition?: null | components["schemas"]["MetaSchemaDefinition"];
      description?: string | null;
      locale?: string | null;
      name?: string | null;
      tags?: string[] | null;
    };
    ValidationDetail: {
      field: string;
      problem: string;
    };
    /**
     * @description Diff result describing whether a metaschema change is backward compatible.
     *     When `is_breaking = true`, the caller must INSERT a new version row.
     */
    VersioningDiff: {
      is_breaking: boolean;
      reasons: string[];
    };
    WorkspaceDetail: {
      /** Format: date-time */
      created_at: string;
      /** Format: int64 */
      entity_count: number;
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      max_entities?: number | null;
      name: string;
      /** Format: int64 */
      relation_count: number;
      /**
       * Format: int64
       * @description Currently *active* schemas only (one per distinct schema name): not a raw row count, which would also include archived versions.
       */
      schema_count: number;
      /** Format: uuid */
      schema_id?: string | null;
      /** Format: uuid */
      tenant_id: string;
    };
    WorkspaceRecord: {
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      embedding_dimensions?: number | null;
      /**
       * @description The embedding model this workspace's vectors were produced by, and their dimension count.
       *     `None` on both means the deployment default: what every workspace created before the stamp existed means, and what a deployment that has never changed models keeps meaning.
       *
       *     Stamped at creation and not edited: changing the model means re-embedding every entity, which is `admin resync-embeddings` rather than a column write.
       */
      embedding_model?: string | null;
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      max_entities?: number | null;
      name: string;
      /** Format: uuid */
      schema_id?: string | null;
      /**
       * @description `schema_pending` until the workspace's first schema exists, `active` from then on.
       *     Entity writes are refused while pending.
       */
      status: string;
      /** Format: uuid */
      tenant_id: string;
    };
    WorkspaceSummary: {
      /** Format: uuid */
      id: string;
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_entities: {
    parameters: {
      query?: {
        entity_type?: string | null;
        /** @description JSON-encoded containment filter, e.g. `{"status":"active"}`. */
        filter?: string | null;
        /** @description Restricts results to entities created against this schema version. */
        schema_version?: number | null;
        limit?: number | null;
        offset?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of entities retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityRecord"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  create_entity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEntityRequest"];
      };
    };
    responses: {
      /** @description Entity created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The specified schema or entity_type does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description data does not conform to the schema */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Entity ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Entity retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Entity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  update_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Entity ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateEntityRequest"];
      };
    };
    responses: {
      /** @description Entity updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Entity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description data does not conform to the schema */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  delete_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Entity ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Entity deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Entity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_entity_context: {
    parameters: {
      query?: {
        /** @description Maximum number of relations/neighbors to include per hop (defaults to 20 if omitted). */
        limit?: number | null;
        /** @description When true, neighbor entities include every field instead of only `x-embed` fields (defaults to false). */
        full?: boolean | null;
        /** @description How many hops to traverse outward from the entity (defaults to 1, max 3). */
        depth?: number | null;
      };
      header?: never;
      path: {
        /** @description Entity ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Entity, its relations, and connected neighbors (up to `depth` hops away) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecallContext"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Entity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_entity_drift: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Entity id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description How the entity stands against its schema's active version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityDrift"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Entity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  export_jsonl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON Lines export of every schema, entity, and relation for the tenant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/x-ndjson": unknown;
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  import_jsonl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description JSON Lines document in the export format */
    requestBody: {
      content: {
        "application/x-ndjson": string;
      };
    };
    responses: {
      /** @description Every record in the body was imported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportResult"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description A line was malformed, or a record failed validation (e.g. unknown schema/entity reference) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_members: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members of the caller's tenant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MembershipRecord"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  add_member: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddMemberRequest"];
      };
    };
    responses: {
      /** @description Membership added (or role changed if already a member) */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MembershipRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description No user with this email has an account */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  undo_migration_job: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Job id from a fill-defaults run */
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description What was put back */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UndoReport"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description No snapshots for that job */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_relations: {
    parameters: {
      query?: {
        source_id?: string | null;
        target_id?: string | null;
        relation_type?: string | null;
        /**
         * @description Restricts the listing to one state.
         *     Omitted, every state is listed.
         */
        status?: string | null;
        limit?: number | null;
        offset?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of relations retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationRecord"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  create_relation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRelationRequest"];
      };
    };
    responses: {
      /** @description Relation created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The source, target, or relation_type does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description An identical relation already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description relation_type conflicts with the entity_type of source/target */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_relation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Relation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relation retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Relation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  delete_relation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Relation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relation deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Relation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  set_relation_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Relation id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetRelationStatusRequest"];
      };
    };
    responses: {
      /** @description Status updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The relation does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a relation status */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_schemas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Summary list of all schemas for the tenant (all versions, including archived) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchemaSummary"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  create_schema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSchemaRequest"];
      };
    };
    responses: {
      /** @description Schema newly registered, or added as a new version */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateSchemaResponse"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The specified template_id does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Version conflict due to concurrent creation */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The schema definition itself is invalid */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_active_schema: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Schema name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Currently active schema definition retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchemaRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description No active schema exists with the given name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_entity_type_json_schema: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Name of the active schema */
        name: string;
        /** @description Name of the entity_type within the schema */
        entity_type: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Result of projecting the entity_type as a JSON Schema */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The specified schema or entity_type does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  fill_defaults: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Schema name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description What was filled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FillDefaultsReport"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description No active schema with that name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  migration_dry_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Schema name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description What a migration to the active version would face */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MigrationDryRun"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description No active schema with that name */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_schema_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Schema ID (specific version) */
        schema_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Schema definition for the specified version retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchemaRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The specified schema does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  search_entities: {
    parameters: {
      query: {
        query_text: string;
        entity_type?: string | null;
        /** @description JSON-encoded containment filter, e.g. `{"status":"active"}`. */
        filter?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vector similarity search results for a natural-language query */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchHit"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_maintenance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The current state */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceResponse"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  set_maintenance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetMaintenanceRequest"];
      };
    };
    responses: {
      /** @description The state as it now stands */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceResponse"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Unknown mode */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_template_library: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Templates visible to the caller's tenant (own plus any community-visible ones) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateRecord"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  create_template: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTemplateRequest"];
      };
    };
    responses: {
      /** @description Template created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description A template with this name already exists for the tenant */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The template definition failed validation */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_template_library_item: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Template detail */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Template not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  update_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTemplateRequest"];
      };
    };
    responses: {
      /** @description Template updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Template not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The template definition failed validation */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  delete_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Template deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Template not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  fork_template_library_item: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template ID to fork */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForkTemplateRequest"];
      };
    };
    responses: {
      /** @description Forked copy of the template, owned by the caller's tenant */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Source template not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description A template with this name already exists for the tenant */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_templates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Built-in schema templates available for schema creation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateSummary"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template ID (e.g. task-management) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full template definition */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetaSchemaDefinition"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Insufficient scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Template not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_workspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspaces belonging to the caller's tenant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceRecord"][];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  create_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Workspace created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceRecord"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description The tenant has reached its workspace limit */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace detail, including entity/relation/schema counts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceDetail"];
        };
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  delete_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace (and everything under it) deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or missing credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a tenant owner/admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description This is the tenant's only workspace */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description A freshly issued API key, scoped to the caller's membership role */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Invalid email or password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Not a member of this workspace's tenant, or of any tenant at all */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description workspace_id omitted, and the account can reach more than one workspace. `details` carries one entry per candidate: `field` is the workspace id and `problem` its name, so a client can offer a picker */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Too many requests from this caller; retry later */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description Account created from a valid invite */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignupResponse"];
        };
      };
      /** @description A user with this email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Invite token is invalid, expired, or already used */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Too many requests from this caller; retry later */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetupRequest"];
      };
    };
    responses: {
      /** @description Deployment initialized: tenant, workspace, and owner account created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetupResponse"];
        };
      };
      /** @description The setup wizard is disabled on this deployment (YORISHIRO_MAX_TENANTS resolves to unlimited) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description This deployment has already been set up */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Too many requests from this caller; retry later */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setup_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whether first-run setup should be shown */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetupStatusResponse"];
        };
      };
    };
  };
}
