//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "content_entities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub schema_id: Uuid,
    pub schema_version: i32,
    #[sea_orm(column_type = "Text")]
    pub entity_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub updated_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::content_entity_embeddings::Entity")]
    ContentEntityEmbeddings,
    #[sea_orm(
        belongs_to = "super::content_schemas::Entity",
        from = "Column::SchemaId",
        to = "super::content_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ContentSchemas,
    #[sea_orm(
        belongs_to = "super::identity_users::Entity",
        from = "Column::CreatedBy",
        to = "super::identity_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IdentityUsers2,
    #[sea_orm(
        belongs_to = "super::identity_users::Entity",
        from = "Column::UpdatedBy",
        to = "super::identity_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IdentityUsers1,
    #[sea_orm(
        belongs_to = "super::identity_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::identity_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityWorkspaces,
}

impl Related<super::content_entity_embeddings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntityEmbeddings.def()
    }
}

impl Related<super::content_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSchemas.def()
    }
}

impl Related<super::identity_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityWorkspaces.def()
    }
}
