//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "content_schemas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub tenant_id: Uuid,
    #[sea_orm(unique_key = "schemas_workspace_name_version_key")]
    #[sea_orm(column_type = "Text")]
    pub workspace_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "schemas_workspace_name_version_key"
    )]
    pub name: String,
    #[sea_orm(unique_key = "schemas_workspace_name_version_key")]
    pub version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub definition: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub origin_template_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub origin_status: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub origin_snapshot: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_entities::Entity")]
    ContentEntities,
    #[sea_orm(
        belongs_to = "super::identity_templates::Entity",
        from = "Column::OriginTemplateId",
        to = "super::identity_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IdentityTemplates,
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
    #[sea_orm(
        belongs_to = "super::identity_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::identity_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityWorkspaces,
}

impl Related<super::content_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntities.def()
    }
}

impl Related<super::identity_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplates.def()
    }
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}

impl Related<super::identity_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityWorkspaces.def()
    }
}
