//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "content_entity_embeddings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub entity_id: Uuid,
    pub embedding: Option<PgVector>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::content_entities::Entity",
        from = "Column::EntityId",
        to = "super::content_entities::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContentEntities,
}

impl Related<super::content_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntities.def()
    }
}
