//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "content_fill_proposals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "fill_proposals_workspace_job_entity_field_key")]
    pub job_id: Uuid,
    #[sea_orm(unique_key = "fill_proposals_workspace_job_entity_field_key")]
    pub workspace_id: Uuid,
    #[sea_orm(unique_key = "fill_proposals_workspace_job_entity_field_key")]
    pub entity_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "fill_proposals_workspace_job_entity_field_key"
    )]
    pub field_name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub proposed: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::identity_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityWorkspaces,
}

impl Related<super::identity_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityWorkspaces.def()
    }
}
