//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "entity_relations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "entity_relations_unique")]
    pub workspace_id: Uuid,
    #[sea_orm(unique_key = "entity_relations_unique")]
    pub source_id: Uuid,
    #[sea_orm(unique_key = "entity_relations_unique")]
    pub target_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "entity_relations_unique")]
    pub relation_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub properties: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entity_entities::Entity",
        from = "Column::SourceId",
        to = "super::entity_entities::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntityEntities2,
    #[sea_orm(
        belongs_to = "super::entity_entities::Entity",
        from = "Column::TargetId",
        to = "super::entity_entities::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntityEntities1,
    #[sea_orm(
        belongs_to = "super::workspace_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkspaceWorkspaces,
}

impl Related<super::workspace_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkspaces.def()
    }
}
