//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "entity_entities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub workspace_id: Uuid,
    pub schema_id: Uuid,
    pub schema_version: i32,
    #[sea_orm(column_type = "Text")]
    pub entity_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schema_schemas::Entity",
        from = "Column::SchemaId",
        to = "super::schema_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SchemaSchemas,
    #[sea_orm(
        belongs_to = "super::user_users::Entity",
        from = "Column::CreatedBy",
        to = "super::user_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UserUsers2,
    #[sea_orm(
        belongs_to = "super::user_users::Entity",
        from = "Column::UpdatedBy",
        to = "super::user_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UserUsers1,
    #[sea_orm(
        belongs_to = "super::workspace_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkspaceWorkspaces,
}

impl Related<super::schema_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchemaSchemas.def()
    }
}

impl Related<super::workspace_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkspaces.def()
    }
}
