//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_api_key_audit_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub workspace_id: Uuid,
    pub tenant_id: Uuid,
    pub api_key_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub detail: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
    #[sea_orm(
        belongs_to = "super::identity_users::Entity",
        from = "Column::UserId",
        to = "super::identity_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IdentityUsers,
    #[sea_orm(
        belongs_to = "super::identity_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::identity_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityWorkspaces,
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}

impl Related<super::identity_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityUsers.def()
    }
}

impl Related<super::identity_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityWorkspaces.def()
    }
}
