//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "users_oauth_identity_idx"
    )]
    pub oauth_provider: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "users_oauth_identity_idx"
    )]
    pub oauth_subject_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::identity_api_key_audit_log::Entity")]
    IdentityApiKeyAuditLog,
    #[sea_orm(has_many = "super::identity_api_keys::Entity")]
    IdentityApiKeys,
    #[sea_orm(has_many = "super::identity_template_reviews::Entity")]
    IdentityTemplateReviews,
    #[sea_orm(has_many = "super::identity_template_versions::Entity")]
    IdentityTemplateVersions,
    #[sea_orm(has_many = "super::identity_templates::Entity")]
    IdentityTemplates,
    #[sea_orm(has_many = "super::identity_tenant_memberships::Entity")]
    IdentityTenantMemberships,
}

impl Related<super::identity_api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityApiKeyAuditLog.def()
    }
}

impl Related<super::identity_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityApiKeys.def()
    }
}

impl Related<super::identity_template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplateReviews.def()
    }
}

impl Related<super::identity_template_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplateVersions.def()
    }
}

impl Related<super::identity_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplates.def()
    }
}

impl Related<super::identity_tenant_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenantMemberships.def()
    }
}
