//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_workspace_llm_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub base_url: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    #[sea_orm(column_type = "Text")]
    pub api_key: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::identity_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityWorkspaces,
}

impl Related<super::identity_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityWorkspaces.def()
    }
}
