//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_maintenance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: bool,
    #[sea_orm(column_type = "Text")]
    pub mode: String,
    pub retry_after: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
