//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_tenant_memberships")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_tenant_memberships_tenant_id_user_id")]
    #[sea_orm(column_type = "Text")]
    pub tenant_id: Uuid,
    #[sea_orm(unique_key = "uq_tenant_memberships_tenant_id_user_id")]
    #[sea_orm(column_type = "Text")]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
    #[sea_orm(
        belongs_to = "super::identity_users::Entity",
        from = "Column::UserId",
        to = "super::identity_users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityUsers,
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}

impl Related<super::identity_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityUsers.def()
    }
}
