//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_tenant_reindex_schedules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tenant_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub interval: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub timezone: Option<String>,
    pub scheduled_for: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}
