//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub max_workspaces: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_schemas::Entity")]
    ContentSchemas,
    #[sea_orm(has_many = "super::identity_api_key_audit_log::Entity")]
    IdentityApiKeyAuditLog,
    #[sea_orm(has_many = "super::identity_api_keys::Entity")]
    IdentityApiKeys,
    #[sea_orm(has_many = "super::identity_invites::Entity")]
    IdentityInvites,
    #[sea_orm(has_many = "super::identity_template_reviews::Entity")]
    IdentityTemplateReviews,
    #[sea_orm(has_many = "super::identity_templates::Entity")]
    IdentityTemplates,
    #[sea_orm(has_one = "super::identity_tenant_billing::Entity")]
    IdentityTenantBilling,
    #[sea_orm(has_many = "super::identity_tenant_memberships::Entity")]
    IdentityTenantMemberships,
    #[sea_orm(has_many = "super::identity_workspaces::Entity")]
    IdentityWorkspaces,
}

impl Related<super::content_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSchemas.def()
    }
}

impl Related<super::identity_api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityApiKeyAuditLog.def()
    }
}

impl Related<super::identity_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityApiKeys.def()
    }
}

impl Related<super::identity_invites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityInvites.def()
    }
}

impl Related<super::identity_template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplateReviews.def()
    }
}

impl Related<super::identity_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplates.def()
    }
}

impl Related<super::identity_tenant_billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenantBilling.def()
    }
}

impl Related<super::identity_tenant_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenantMemberships.def()
    }
}

impl Related<super::identity_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityWorkspaces.def()
    }
}
