//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "templates_tenant_id_name_key")]
    pub tenant_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "templates_tenant_id_name_key")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub definition: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub locale: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub visibility: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub author: Option<String>,
    pub fork_of: Option<Uuid>,
    pub created_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub tags: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_schemas::Entity")]
    ContentSchemas,
    #[sea_orm(has_many = "super::identity_template_reviews::Entity")]
    IdentityTemplateReviews,
    #[sea_orm(has_many = "super::identity_template_versions::Entity")]
    IdentityTemplateVersions,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ForkOf",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IdentityTenants,
    #[sea_orm(
        belongs_to = "super::identity_users::Entity",
        from = "Column::CreatedBy",
        to = "super::identity_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IdentityUsers,
}

impl Related<super::content_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSchemas.def()
    }
}

impl Related<super::identity_template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplateReviews.def()
    }
}

impl Related<super::identity_template_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplateVersions.def()
    }
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}

impl Related<super::identity_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityUsers.def()
    }
}
