//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_template_reviews")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(unique_key = "template_reviews_template_id_tenant_id_key")]
    #[sea_orm(column_type = "Text")]
    pub template_id: Uuid,
    #[sea_orm(unique_key = "template_reviews_template_id_tenant_id_key")]
    #[sea_orm(column_type = "Text")]
    pub tenant_id: Uuid,
    pub rating: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_templates::Entity",
        from = "Column::TemplateId",
        to = "super::identity_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTemplates,
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
    #[sea_orm(
        belongs_to = "super::identity_users::Entity",
        from = "Column::CreatedBy",
        to = "super::identity_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IdentityUsers,
}

impl Related<super::identity_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTemplates.def()
    }
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}

impl Related<super::identity_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityUsers.def()
    }
}
