//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_workspaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "identity_workspaces_tenant_id_name_key")]
    pub tenant_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "identity_workspaces_tenant_id_name_key"
    )]
    pub name: String,
    pub max_entities: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_model: Option<String>,
    pub embedding_dimensions: Option<i32>,
    pub schema_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_entities::Entity")]
    ContentEntities,
    #[sea_orm(has_many = "super::content_entity_snapshots::Entity")]
    ContentEntitySnapshots,
    #[sea_orm(has_many = "super::content_relations::Entity")]
    ContentRelations,
    #[sea_orm(
        belongs_to = "super::content_schemas::Entity",
        from = "Column::SchemaId",
        to = "super::content_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ContentSchemas,
    #[sea_orm(has_many = "super::identity_api_keys::Entity")]
    IdentityApiKeys,
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
}

impl Related<super::content_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntities.def()
    }
}

impl Related<super::content_entity_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntitySnapshots.def()
    }
}

impl Related<super::content_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentRelations.def()
    }
}

impl Related<super::content_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSchemas.def()
    }
}

impl Related<super::identity_api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityApiKeys.def()
    }
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}
