//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_invites")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub tenant_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", unique)]
    pub token_hash: Vec<u8>,
    pub expires_at: DateTimeWithTimeZone,
    pub used_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_tenants::Entity",
        from = "Column::TenantId",
        to = "super::identity_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityTenants,
}

impl Related<super::identity_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityTenants.def()
    }
}
