//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "inference_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub schema_name: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub applied: i64,
    pub skipped: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::workspace_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkspaceWorkspaces,
}

impl Related<super::workspace_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkspaces.def()
    }
}
