//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "queue_job_lifecycles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub provider_job_id: Option<String>,
    pub job_name: String,
    pub worker_class: String,
    pub workspace_id: Option<Uuid>,
    pub plan: Option<String>,
    pub status: String,
    pub enqueue_at: DateTimeWithTimeZone,
    pub claim_at: Option<DateTimeWithTimeZone>,
    pub start_at: Option<DateTimeWithTimeZone>,
    pub retry_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub failed_at: Option<DateTimeWithTimeZone>,
    pub cancelled_at: Option<DateTimeWithTimeZone>,
    pub attempt: i32,
    pub concurrency_key: Option<String>,
    pub concurrency_limit: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub admitted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
