//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "queue_job_dispatch_outbox")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub lifecycle_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub worker_name: String,
    pub queue_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    pub last_attempt_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
