//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "schema_schemas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    #[sea_orm(unique_key = "schema_schemas_workspace_name_version_key")]
    pub workspace_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "schema_schemas_workspace_name_version_key"
    )]
    pub name: String,
    #[sea_orm(unique_key = "schema_schemas_workspace_name_version_key")]
    pub version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub definition: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub origin_template_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub origin_status: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub origin_snapshot: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub origin_updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::entity_entities::Entity")]
    EntityEntities,
    #[sea_orm(
        belongs_to = "super::template_templates::Entity",
        from = "Column::OriginTemplateId",
        to = "super::template_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TemplateTemplates,
    #[sea_orm(
        belongs_to = "super::tenant_tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenant_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TenantTenants,
    #[sea_orm(
        belongs_to = "super::workspace_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkspaceWorkspaces,
}

impl Related<super::entity_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityEntities.def()
    }
}

impl Related<super::template_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateTemplates.def()
    }
}

impl Related<super::tenant_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantTenants.def()
    }
}

impl Related<super::workspace_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkspaces.def()
    }
}
