//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "template_templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "template_templates_tenant_id_name_key")]
    pub tenant_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "template_templates_tenant_id_name_key"
    )]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub definition: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub locale: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub visibility: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub author: Option<String>,
    pub fork_of: Option<Uuid>,
    pub created_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub tags: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::schema_schemas::Entity")]
    SchemaSchemas,
    #[sea_orm(has_many = "super::template_reviews::Entity")]
    TemplateReviews,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ForkOf",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::template_versions::Entity")]
    TemplateVersions,
    #[sea_orm(
        belongs_to = "super::tenant_tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenant_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TenantTenants,
    #[sea_orm(
        belongs_to = "super::user_users::Entity",
        from = "Column::CreatedBy",
        to = "super::user_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UserUsers,
}

impl Related<super::schema_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchemaSchemas.def()
    }
}

impl Related<super::template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateReviews.def()
    }
}

impl Related<super::template_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateVersions.def()
    }
}

impl Related<super::tenant_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantTenants.def()
    }
}

impl Related<super::user_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserUsers.def()
    }
}
