//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub max_workspaces: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_model: Option<String>,
    pub embedding_dimensions: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_audit_log::Entity")]
    ApiKeyAuditLog,
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::content_schemas::Entity")]
    ContentSchemas,
    #[sea_orm(has_many = "super::invites::Entity")]
    Invites,
    #[sea_orm(has_many = "super::template_reviews::Entity")]
    TemplateReviews,
    #[sea_orm(has_many = "super::templates::Entity")]
    Templates,
    #[sea_orm(has_one = "super::tenant_billing::Entity")]
    TenantBilling,
    #[sea_orm(has_many = "super::tenant_memberships::Entity")]
    TenantMemberships,
    #[sea_orm(has_many = "super::workspaces::Entity")]
    Workspaces,
}

impl Related<super::api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyAuditLog.def()
    }
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::content_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSchemas.def()
    }
}

impl Related<super::invites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invites.def()
    }
}

impl Related<super::template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateReviews.def()
    }
}

impl Related<super::templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Templates.def()
    }
}

impl Related<super::tenant_billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantBilling.def()
    }
}

impl Related<super::tenant_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantMemberships.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}
