//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tenant_tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub max_workspaces: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_model: Option<String>,
    pub embedding_dimensions: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_audit_log::Entity")]
    ApiKeyAuditLog,
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::schema_schemas::Entity")]
    SchemaSchemas,
    #[sea_orm(has_many = "super::template_reviews::Entity")]
    TemplateReviews,
    #[sea_orm(has_many = "super::template_templates::Entity")]
    TemplateTemplates,
    #[sea_orm(has_one = "super::tenant_billing::Entity")]
    TenantBilling,
    #[sea_orm(has_many = "super::tenant_memberships::Entity")]
    TenantMemberships,
    #[sea_orm(has_one = "super::tenant_reindex_schedules::Entity")]
    TenantReindexSchedules,
    #[sea_orm(has_many = "super::workspace_invites::Entity")]
    WorkspaceInvites,
    #[sea_orm(has_many = "super::workspace_workspaces::Entity")]
    WorkspaceWorkspaces,
}

impl Related<super::api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyAuditLog.def()
    }
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::schema_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchemaSchemas.def()
    }
}

impl Related<super::template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateReviews.def()
    }
}

impl Related<super::template_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateTemplates.def()
    }
}

impl Related<super::tenant_billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantBilling.def()
    }
}

impl Related<super::tenant_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantMemberships.def()
    }
}

impl Related<super::tenant_reindex_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantReindexSchedules.def()
    }
}

impl Related<super::workspace_invites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceInvites.def()
    }
}

impl Related<super::workspace_workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkspaces.def()
    }
}
