//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "users_oauth_identity_idx"
    )]
    pub oauth_provider: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "users_oauth_identity_idx"
    )]
    pub oauth_subject_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_audit_log::Entity")]
    ApiKeyAuditLog,
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::template_reviews::Entity")]
    TemplateReviews,
    #[sea_orm(has_many = "super::template_versions::Entity")]
    TemplateVersions,
    #[sea_orm(has_many = "super::templates::Entity")]
    Templates,
    #[sea_orm(has_many = "super::tenant_memberships::Entity")]
    TenantMemberships,
}

impl Related<super::api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyAuditLog.def()
    }
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::template_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateReviews.def()
    }
}

impl Related<super::template_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateVersions.def()
    }
}

impl Related<super::templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Templates.def()
    }
}

impl Related<super::tenant_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantMemberships.def()
    }
}
