//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "identity_workspaces_tenant_id_name_key")]
    pub tenant_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "identity_workspaces_tenant_id_name_key"
    )]
    pub name: String,
    pub max_entities: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_model: Option<String>,
    pub embedding_dimensions: Option<i32>,
    pub schema_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_audit_log::Entity")]
    ApiKeyAuditLog,
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::content_entities::Entity")]
    ContentEntities,
    #[sea_orm(has_many = "super::content_entity_column_preferences::Entity")]
    ContentEntityColumnPreferences,
    #[sea_orm(has_many = "super::content_entity_snapshots::Entity")]
    ContentEntitySnapshots,
    #[sea_orm(has_many = "super::content_relations::Entity")]
    ContentRelations,
    #[sea_orm(
        belongs_to = "super::content_schemas::Entity",
        from = "Column::SchemaId",
        to = "super::content_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ContentSchemas,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_one = "super::workspace_embedding_keys::Entity")]
    WorkspaceEmbeddingKeys,
    #[sea_orm(has_one = "super::workspace_llm_keys::Entity")]
    WorkspaceLlmKeys,
    #[sea_orm(has_one = "super::workspace_worker_classes::Entity")]
    WorkspaceWorkerClasses,
}

impl Related<super::api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyAuditLog.def()
    }
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::content_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntities.def()
    }
}

impl Related<super::content_entity_column_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntityColumnPreferences.def()
    }
}

impl Related<super::content_entity_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentEntitySnapshots.def()
    }
}

impl Related<super::content_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentRelations.def()
    }
}

impl Related<super::content_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSchemas.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::workspace_embedding_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceEmbeddingKeys.def()
    }
}

impl Related<super::workspace_llm_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceLlmKeys.def()
    }
}

impl Related<super::workspace_worker_classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkerClasses.def()
    }
}
