//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspace_schema_fork_heads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub workspace_id: Uuid,
    #[sea_orm(unique_key = "workspace_schema_fork_heads_fork_schema_key")]
    pub fork_id: Uuid,
    #[sea_orm(unique_key = "workspace_schema_fork_heads_fork_schema_key")]
    pub schema_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schema_schemas::Entity",
        from = "Column::SchemaId",
        to = "super::schema_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SchemaSchemas,
    #[sea_orm(
        belongs_to = "super::workspace_schema_forks::Entity",
        from = "Column::ForkId",
        to = "super::workspace_schema_forks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkspaceSchemaForks,
}

impl Related<super::schema_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchemaSchemas.def()
    }
}

impl Related<super::workspace_schema_forks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceSchemaForks.def()
    }
}
