//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspace_workspaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "workspace_workspaces_tenant_id_name_key")]
    pub tenant_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "workspace_workspaces_tenant_id_name_key"
    )]
    pub name: String,
    pub max_entities: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_model: Option<String>,
    pub embedding_dimensions: Option<i32>,
    pub schema_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_audit_log::Entity")]
    ApiKeyAuditLog,
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::compute_credit_ledger::Entity")]
    ComputeCreditLedger,
    #[sea_orm(has_many = "super::entity_column_preferences::Entity")]
    EntityColumnPreferences,
    #[sea_orm(has_many = "super::entity_entities::Entity")]
    EntityEntities,
    #[sea_orm(has_many = "super::entity_relations::Entity")]
    EntityRelations,
    #[sea_orm(has_many = "super::entity_snapshots::Entity")]
    EntitySnapshots,
    #[sea_orm(
        belongs_to = "super::schema_schemas::Entity",
        from = "Column::SchemaId",
        to = "super::schema_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SchemaSchemas,
    #[sea_orm(
        belongs_to = "super::tenant_tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenant_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TenantTenants,
    #[sea_orm(has_one = "super::workspace_embedding_keys::Entity")]
    WorkspaceEmbeddingKeys,
    #[sea_orm(has_one = "super::workspace_llm_keys::Entity")]
    WorkspaceLlmKeys,
    #[sea_orm(has_one = "super::workspace_worker_classes::Entity")]
    WorkspaceWorkerClasses,
}

impl Related<super::api_key_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyAuditLog.def()
    }
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::compute_credit_ledger::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComputeCreditLedger.def()
    }
}

impl Related<super::entity_column_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityColumnPreferences.def()
    }
}

impl Related<super::entity_entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityEntities.def()
    }
}

impl Related<super::entity_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityRelations.def()
    }
}

impl Related<super::entity_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntitySnapshots.def()
    }
}

impl Related<super::schema_schemas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchemaSchemas.def()
    }
}

impl Related<super::tenant_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantTenants.def()
    }
}

impl Related<super::workspace_embedding_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceEmbeddingKeys.def()
    }
}

impl Related<super::workspace_llm_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceLlmKeys.def()
    }
}

impl Related<super::workspace_worker_classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceWorkerClasses.def()
    }
}
