//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspace_schema_forks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    #[sea_orm(unique_key = "workspace_schema_forks_workspace_source_name_key")]
    pub workspace_id: Uuid,
    #[sea_orm(unique_key = "workspace_schema_forks_workspace_source_name_key")]
    pub source_workspace_id: Uuid,
    pub source_schema_id: Uuid,
    pub source_schema_version: i32,
    #[sea_orm(
        column_type = "Text",
        unique_key = "workspace_schema_forks_workspace_source_name_key"
    )]
    pub source_schema_name: String,
    pub fork_schema_id: Uuid,
    pub customized: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schema_schemas::Entity",
        from = "Column::ForkSchemaId",
        to = "super::schema_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SchemaSchemas2,
    #[sea_orm(
        belongs_to = "super::schema_schemas::Entity",
        from = "Column::SourceSchemaId",
        to = "super::schema_schemas::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SchemaSchemas1,
    #[sea_orm(
        belongs_to = "super::tenant_tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenant_tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TenantTenants,
    #[sea_orm(
        belongs_to = "super::workspace_workspaces::Entity",
        from = "Column::SourceWorkspaceId",
        to = "super::workspace_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    WorkspaceWorkspaces2,
    #[sea_orm(
        belongs_to = "super::workspace_workspaces::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace_workspaces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkspaceWorkspaces1,
}

impl Related<super::tenant_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TenantTenants.def()
    }
}
