-- The app role writes two columns of identity.workspaces, and held no grant to do either.
--
-- `create_schema` marks a workspace active in the same transaction as the schema insert, so the
-- UPDATE runs as `yorishiro_app` -- which the initial migration granted `SELECT` alone. The
-- `status` column arrived later (workspace_schema_pending) without extending that grant, so
-- every schema creation, over REST and over MCP, failed with `permission denied for table
-- workspaces` and answered 500.
--
-- No test could see it: only the production pool issues `SET ROLE yorishiro_app` (`db.rs`), and
-- `sqlx::test` connects as the owner, where every grant is implicit.
--
-- Column-level rather than table-level, because these two are the whole of what the request path
-- writes here. `max_entities`, `name` and the embedding stamp are provisioning decisions, and a
-- request that could rewrite its own quota is a different system.
GRANT UPDATE (status, schema_id) ON identity.workspaces TO yorishiro_app;
