//! Reusable column/statement builders shared across migration files.
//!
//! `loco_rs::schema::ColType` has no variant that is both a primary key and carries a custom default expression, so every table's `id` column goes through `sea_query::ColumnDef` directly.
//!
//! SQLite has no roles, RLS, or SECURITY DEFINER functions: a single-file database has no other tenant to isolate from.
//! `enable_rls_with_policy`/`grant`/`pg_only` all no-op on that backend rather than each call site branching for itself, so a migration file's Postgres statements stay exactly as written.
use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::DbBackend;

/// Forces every migration to run inside one transaction, on every backend.
/// Postgres already defaults to this. SQLite's own default is `false`
/// (`should_use_transaction`'s own default in sea-orm-migration), which lets a
/// migration's DDL statements interleave across different pooled connections
/// once max_connections > 1. Measured: a DROP TRIGGER/CREATE TRIGGER pair
/// (SQLite has no CREATE OR REPLACE TRIGGER) fails "already exists" under that
/// interleaving. Every migration file's own `use_transaction` override should
/// call this rather than repeating `Some(true)` inline, so a future migration
/// file cannot forget it and reintroduce the bug.
pub fn use_transaction() -> Option<bool> {
    Some(true)
}

/// `id UUID PRIMARY KEY DEFAULT uuidv7()` on Postgres, `id BLOB PRIMARY KEY` on SQLite.
///
/// SQLite has no `uuidv7()` default, so every insert must supply its own id.
/// SeaORM serializes `Uuid` as 16-byte BLOB; storing the column as BLOB lets
/// the entity API's `.filter(Column::Id.eq(uuid))` match on SQLite without
/// the hex-string workaround that TEXT columns required.
pub fn uuidv7_pk(manager: &SchemaManager<'_>) -> ColumnDef {
    let mut col = ColumnDef::new(Alias::new("id"));
    if manager.get_database_backend() == DbBackend::Sqlite {
        col.blob().not_null().primary_key();
    } else {
        col.uuid()
            .not_null()
            .primary_key()
            .default(Expr::cust("uuidv7()"));
    }
    col.to_owned()
}

/// `created_at TIMESTAMP NOT NULL DEFAULT now()`.
///
/// On SQLite the column type is `TEXT` because the custom
/// `timestamp_with_time_zone_text` generated by `sea-query` is not recognised by
/// SQLite (same problem as `uuid_text` / `jsonb_text`).
pub fn created_at(manager: &SchemaManager<'_>) -> ColumnDef {
    let mut col = ColumnDef::new(Alias::new("created_at"));
    if manager.get_database_backend() == DbBackend::Sqlite {
        col.text().not_null().default(Expr::current_timestamp());
    } else {
        col.timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp());
    }
    col.to_owned()
}

/// `created_at` plus `updated_at`, both `TIMESTAMP NOT NULL DEFAULT now()`.
pub fn timestamps(manager: &SchemaManager<'_>) -> [ColumnDef; 2] {
    let ca = created_at(manager);
    let mut ua = ColumnDef::new(Alias::new("updated_at"));
    if manager.get_database_backend() == DbBackend::Sqlite {
        ua.text().not_null().default(Expr::current_timestamp());
    } else {
        ua.timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp());
    }
    [ca, ua.to_owned()]
}

/// Enables RLS and installs a single-column-equality policy in one raw-SQL round trip.
///
/// `column = current_setting(setting)::uuid`, either strict (missing setting raises) or lenient (`lenient => true`, missing setting reads as NULL, matching nothing): strict for tables `yorishiro_app` always reaches with both GUCs set, lenient for tables the control-plane pool also reaches without naming a workspace.
///
/// No-ops on SQLite: a single-tenant, single-file database has no other tenant's rows to hide, so there is no policy to install.
pub async fn enable_rls_with_policy(
    manager: &SchemaManager<'_>,
    table: &str,
    policy_name: &str,
    column: &str,
    setting: &str,
    lenient: bool,
) -> Result<(), DbErr> {
    if manager.get_database_backend() == DbBackend::Sqlite {
        return Ok(());
    }
    let condition = if lenient {
        format!("{column} = NULLIF(current_setting('{setting}', true), '')::uuid")
    } else {
        format!("{column} = current_setting('{setting}')::uuid")
    };
    manager
        .get_connection()
        .execute_unprepared(&format!(
            "ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
         CREATE POLICY {policy_name} ON {table} USING ({condition});"
        ))
        .await?;
    Ok(())
}

/// A single explicit per-table GRANT to `yorishiro_app`.
///
/// Deliberately never a schema-wide `GRANT ... ON ALL TABLES IN SCHEMA public`: that would sweep in the tables that must stay ungranted (`identity_tenants`, `identity_users`, `identity_tenant_memberships`, `identity_invites`, `identity_templates`, `identity_workspace_llm_keys`).
/// Every grant is named here, one call per table, so an ungranted table is ungranted because no call exists for it, not because a wildcard missed it.
///
/// No-ops on SQLite: there is no separate `yorishiro_app` role on that backend, since the process itself is the only tenant.
pub async fn grant(
    manager: &SchemaManager<'_>,
    privileges: &str,
    table: &str,
) -> Result<(), DbErr> {
    if manager.get_database_backend() == DbBackend::Sqlite {
        return Ok(());
    }
    manager
        .get_connection()
        .execute_unprepared(&format!("GRANT {privileges} ON {table} TO yorishiro_app;"))
        .await?;
    Ok(())
}

/// Creates `table`, with each `(constraint_name, expr)` in `checks` applied as a table-level CHECK.
///
/// SQLite's `ALTER TABLE` supports only rename/add-column/drop-column, so a named `ADD CONSTRAINT` after the fact (Postgres's usual shape in this crate) doesn't work there: the checks go inline into the `CREATE TABLE` for SQLite instead, and as `ALTER TABLE ... ADD CONSTRAINT` statements for Postgres.
///
/// SeaORM's `TableAlterStatement` has no `add_constraint` builder — `execute_unprepared` is Loco's own documented pattern for these.
pub async fn create_table_with_checks(
    manager: &SchemaManager<'_>,
    table_name: &str,
    mut table: TableCreateStatement,
    checks: &[(&str, &str)],
) -> Result<(), DbErr> {
    let sqlite = manager.get_database_backend() == DbBackend::Sqlite;
    if sqlite {
        for (_, expr) in checks {
            table = table.check(Expr::cust((*expr).to_owned())).to_owned();
        }
    }
    manager.create_table(table).await?;
    if !sqlite {
        for (name, expr) in checks {
            manager
                .get_connection()
                .execute_unprepared(&format!(
                    "ALTER TABLE {table_name} ADD CONSTRAINT {name} CHECK ({expr});"
                ))
                .await?;
        }
    }
    Ok(())
}

/// Runs `sql` only on Postgres; a no-op on SQLite.
///
/// For raw statements with no SQLite equivalent at all (role creation, column-level GRANTs, `plpgsql` functions/triggers, GIN/HNSW/trigram indexes, pgvector DDL): a table-scoped CHECK that SQLite *can* express instead moves into that table's `Table::create()` for the SQLite backend rather than routing through here, since skipping it there would silently drop a real constraint rather than an engine-specific optimization.
pub async fn pg_only(manager: &SchemaManager<'_>, sql: &str) -> Result<(), DbErr> {
    if manager.get_database_backend() == DbBackend::Sqlite {
        return Ok(());
    }
    manager.get_connection().execute_unprepared(sql).await?;
    Ok(())
}

/// Runs `sql` only on SQLite; a no-op on Postgres.
///
/// For the SQLite-specific replacement half of a `pg_only` statement (a trigger written in SQLite's own trigger syntax rather than `plpgsql`, for example), kept as its own call at the same call site as the Postgres original rather than folded into one branching statement, so both versions stay independently greppable.
pub async fn sqlite_only(manager: &SchemaManager<'_>, sql: &str) -> Result<(), DbErr> {
    if manager.get_database_backend() != DbBackend::Sqlite {
        return Ok(());
    }
    manager.get_connection().execute_unprepared(sql).await?;
    Ok(())
}

/// A UUID column: `BLOB` on SQLite, `UUID` on PostgreSQL.
///
/// SeaORM serializes `Uuid` as 16-byte BLOB.
/// Storing UUID columns as BLOB on SQLite aligns the column affinity with the bind format, so FK comparisons and `.filter()` work without hex-string conversion.
pub fn uuid_col(manager: &SchemaManager<'_>, name: Alias) -> ColumnDef {
    let mut col = ColumnDef::new(name);
    if manager.get_database_backend() == DbBackend::Sqlite {
        col.blob();
    } else {
        col.uuid();
    }
    col.to_owned()
}

/// A JSON column: `TEXT` on SQLite, `JSONB` on PostgreSQL.
///
/// `sea-query`'s `json_binary()` generates `jsonb_text` for SQLite, but the
/// `sqlite-vec` 0.1.9 version in this deployment does not provide a `jsonb_text`
/// custom type, so SQLite rejects text data as `datatype mismatch` against the
/// unknown column type.  `TEXT` works identically for both backends: `serde_json`
/// round-trips the same either way.
pub fn json_col(manager: &SchemaManager<'_>, name: Alias) -> ColumnDef {
    let mut col = ColumnDef::new(name);
    if manager.get_database_backend() == DbBackend::Sqlite {
        col.text();
    } else {
        col.json_binary();
    }
    col.to_owned()
}

/// A `TIMESTAMPTZ` column: `TEXT` on SQLite, `TIMESTAMPTZ` on PostgreSQL.
///
/// Same problem as `uuid_text` / `jsonb_text`: the custom SQLite column type
/// is not recognised as text affinity.
pub fn ts_tz_col(manager: &SchemaManager<'_>, name: Alias) -> ColumnDef {
    let mut col = ColumnDef::new(name);
    if manager.get_database_backend() == DbBackend::Sqlite {
        col.text();
    } else {
        col.timestamp_with_time_zone();
    }
    col.to_owned()
}
