[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"
codegen-units = 16

[profile.dev.build-override]
debug = false

[profile.test]
debug = "line-tables-only"
split-debuginfo = "unpacked"
